Калькулятор
js-tasks-ru/vue-20211116_mihail-kozlov3 pull request #2
Opened 2021-11-28 11:02 UTC by MorroLuarvik

Единственное, что смущает, множественные ватчеры

2021-11-28 11:03 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-28 11:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-11-28 11:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-11-29 01:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-11-29 01:25 UTC, MorroLuarvik commented
В случае калькулятора избавился от множественных вотчеров, сделал результат компьютед

2021-11-29 20:16 UTC, ShGKme requested changes
Требуется ещё небольшая правка в 03-MarkedList, предыдущая задача принята.

2021-11-29 20:16 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  }
Вместо вычисления в вычисляемом свойстве класса для шаблона лучше вычислить флаг о необходимости маркировки, и уже в шаблоне привязывать класс к этому флагу.

Тогда всё, что относится к вёрстке (имя класса) останется в шаблоне, где описано, от чего он зависит. А в приложении будут данные о маркировки, которые можно использовать не только для вывода.

2021-11-29 20:16 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  }
Для практики эту часть решения предлагает обновить.

2021-11-29 23:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-29 23:18 UTC, MorroLuarvik commented on 01-basics/03-MarkedList/script.js
> +  }
Согласен. Стили должны быть в шаблоне, в vue классе - логика.  
Исправил, название css класса определяется в шаблоне, а Vue app возвращает логический параметр.

2021-11-30 05:39 UTC, ShGKme reviewed
Изменения приняты, но осталась нерешённая добавленная задача

2021-11-30 08:53 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-30 10:50 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +}).mount("#app")
Не похоже на решение :)

2021-11-30 10:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-30 11:00 UTC, MorroLuarvik commented on 01-basics/04-MeetupTitle/script.js
> +}).mount("#app")
Прошу, прощения, это было не решение, а преждевременный пуш.  
Отправил изменения.  

Надеюсь promis'ами воспользовался правильно, они для меня внове.

2021-11-30 11:25 UTC, ShGKme approved these changes
Все задачи приняты

2021-11-30 11:26 UTC, merged